### PR TITLE
Python3 and Retina

### PR DESCRIPTION
**Pull request by JonKoser**
This PR updates the code to Python3 and fixes the retina display issues for OSX.

I haven't written issues for these so if you'd like me to do that first, please let me know.

### CODE REVIEW

**Comment by JonKoser** [comment]
Oh yeah, Tkinter -> tkinter.
Maybe this should be a brand-new repo...

**Comment by matejc** [comment]
@JonKoser Hey, thank you for this pull request. I have reviewed it, it works as expected on python 3.x. Do you have any unfinished work before we merge this into master?

**Comment by JonKoser** [comment]
I have another branch which adds a confidence level for OpenCV image recognition, but I can set that up as a separate PR. Thanks for looking over this!

**Comment by JonKoser** [comment]
Alternatively, I could merge it to this. Which do you prefer?

**Comment by matejc** [comment]
I have been looking into OpenCV's confidence level also, but if you had done it already - perfect! But yes, that's for another pull request!

**Pull request merged**
